import { ProductDetails } from "../Helper/types";

export const Items: ProductDetails[] = [
  {
    id: 1,
    name: "Johnson's Baby Shampoo",
    category: "Baby Care",
    mrp: 199,
    sellingPrice: 179,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Himalaya Baby Cream",
    category: "Baby Care",
    mrp: 149,
    sellingPrice: 129,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Samsung Smart Watch",
    category: "Electronics",
    mrp: 9999,
    sellingPrice: 8999,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Dove Body Wash",
    category: "Bath & Body",
    mrp: 299,
    sellingPrice: 249,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Colgate Toothpaste",
    category: "Oral Care",
    mrp: 99,
    sellingPrice: 89,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "L'Oreal Hair Serum",
    category: "Hair Care",
    mrp: 399,
    sellingPrice: 349,
    image: "https://m.media-amazon.com/images/I/61QYw6QZJZL._SL1500_.jpg",
    quantity: 1,
  },
];
